#!/bin/sh

_BASE="$(/usr/bin/basename $(git config --get remote.origin.url))"
_NAME="$_BASE"
if [[ $_BASE == *-container.git* ]] ; then
 _NAME=${_BASE%-container.git}
fi

set -a
if [ -f "./args.conf" ] ; then
 source ./args.conf
fi
if [ -f "./.args.conf" ] ; then
 source ./.args.conf
fi
if [ -f "./envs.conf" ] ; then
 source ./envs.conf
fi
if [ -f "./.envs.conf" ] ; then
 source ./.envs.conf
fi
set +a

if [ -z $PUBLISH_REPOSITORY ] ; then
 echo "PUBLISH_REPOSITORY not found"
 exit 1
fi

if [ -z $DOCKERIO_USERNAME ] ; then
 echo "DOCKERIO_USERNAME not found"
 exit 1
fi

TAG="podman tag 'localhost/$_NAME:build' '$PUBLISH_REPOSITORY/$DOCKERIO_USERNAME/$_NAME:$1'"
echo "$TAG"
/bin/sh -c "$TAG"




