#!/bin/sh

_ENVS=""
if [ -f "envs.conf" ] ; then
 _ENVS="--env-file envs.conf "
fi
if [ -f ".envs.conf" ] ; then
 _ENVS="$_ENVS --env-file .envs.conf"
fi
RUN="podman run $_ENVS --interactive --name $(/usr/bin/basename $(pwd)) --publish-all --replace --rm --tty"
 RUN="$RUN --volume Container:/mnt/volumes/container"
 RUN="$RUN --volume Backup:/mnt/volumes/backup"
 RUN="$RUN --volume Configmaps:/mnt/volumes/configmaps"
 RUN="$RUN --volume Secrets:/mnt/volumes/secrets"
 RUN="$RUN localhost/$(/usr/bin/basename $(pwd)):build $@"
 echo "$RUN"
 /bin/sh -c "$RUN"