#!/bin/sh

echo "*****"
_SERVICE="$(pwd | awk -F'/' '{print $NF}')"
echo $_SERVICE
_CONTAINERS="$(/usr/local/bin/docker ps --filter 'ancestor=$(echo $_SERVICE):dev' --quiet | xargs)"
echo "&&&&&&"
XYZ="$(echo $_CONTAINERS | xargs)"
echo "%%%%%%%%"
# _COUNT="$(echo $_CONTAINERS | wc -l)"
# echo $_COUNT
# _COUNT=$(($_COUNT-1))
# echo $_COUNT
echo "$XYZ"
# if [ -z "$_CONTAINERS" ] ; then
#  /usr/local/bin/docker rm "$_CONTAINERS"
# fi
# echo "$?"
# /usr/local/bin/docker compose run --service-ports --detach $(pwd | awk -F'/' '{print $NF}') 
# /usr/local/bin/docker ps --all
