#!/bin/sh
# _BASE="$(/usr/bin/basename $(pwd))"
_BASE="$(/usr/bin/basename $(git rev-parse --show-toplevel))"
_NAME="$_BASE"
if [[ $_BASE == *-container* ]] ; then
 _NAME=${_BASE%-container}
fi
# if [ $_BASE -eq "src"] ; then
#  _NAME="$(/usr/bin/dirname $(pwd))"
# fi
echo $_NAME
