#!/bin/sh

_BASE="$(/usr/bin/basename $(pwd))"
_NAME="$_BASE"
if [[ $_BASE == *-container* ]]; then
 _NAME=${_BASE%-container}
fi

set -a
if [ -f "./args.conf" ] ; then
 source ./args.conf
fi
if [ -f "./envs.conf" ] ; then
 source ./envs.conf
fi
set +a

TAG="podman tag 'localhost/$_NAME:build' '$PUBLISH_REPOSITORY/$DOCKERIO_USERNAME/$_NAME:$1'"
echo "$TAG"
/bin/sh -c "$TAG"




