#!/bin/zsh

docker-compose-build() {
 /usr/local/bin/docker compose build $(pwd | awk -F'/' '{print $NF}') $@ 
 # echo "$(pwd | awk -F'/' '{print $NF}')"
}

docker-compose-run() {
 /usr/local/bin/docker compose run --service-ports  $(pwd | awk -F'/' '{print $NF}') "$@"
}


