#!/bin/zsh

# functions - This is a collection of functions for the default shell, used across MacOS, Alpine, and Debian.

container-compose() {
 if [ -f "/usr/bin/podman-compose" ] ; then
  /usr/bin/podman-compose $@
 else
  if [ -f "/usr/local/bin/docker" ] ; then
   /usr/local/bin/docker compose $@
  fi
 fi
#  else
#   if [ -f "/usr/bin/docker" ] ; then
#    echo "/usr/bin/docker compose"
#   else
#    echo "No compose app found"
#    exit 1
#   fi
#  fi
}

container-kubectl() {
 echo "FUNCTION"

 if [ -f "/usr/bin/kubectl" ] ; then
  /usr/bin/kubectl $@
 else
  if [ -f "/usr/local/bin/kubectl" ] ; then
   /usr/local/bin/kubectl $@
  fi
 fi
}



# container-compose-build() {
#  $(container-compose build $(pwd | awk -F'/' '{print $NF}') $@)
# }
# 
# container-compose-run() {
#  $(container-compose run --service-ports  $(pwd | awk -F'/' '{print $NF}') "$@")
# }


