#!/bin/zsh

podman-compose-build() {
 /usr/bin/podman-compose build $(pwd | awk -F'/' '{print $NF}') $@ 
 # echo "$(pwd | awk -F'/' '{print $NF}')"
}

podman-compose-run() {
 /usr/bin/podman-compose run --service-ports  $(pwd | awk -F'/' '{print $NF}') "$@"
}


